language: python

before_install:
  - sudo apt-get install -y zsh

install:
  - pip install -r requirements-ci.txt -r requirements.txt

env:
  - TOXENV=py27 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py34 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py35 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py35 TESTOPTS=--shell=bash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py35 TESTOPTS=--shell=zsh TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py36 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py36 TESTOPTS=--shell=bash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=py36 TESTOPTS=--shell=zsh TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=pypy TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=pypy3 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=flake8 TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"
  - TOXENV=manifest TESTOPTS=--shell=dash TOX_TESTENV_PASSENV="TESTOPTS"

script:
  - tox
