package:
  name: cram
  version: "0.7"

source:
  path: ../
#  fn: cram-0.7.tar.gz
#  url: https://pypi.python.org/packages/38/85/5a8a3397b2ccb2ffa3ba871f76a4d72c16531e43d0e58fc89a0f2983adbd/cram-0.7.tar.gz
#  md5: 2ea37ada5190526b9bcaac5e4099221c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cram = cram:main
    #
    # Would create an entry point called cram that calls cram.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - cram

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitheap.org/cram/
  license: GNU General Public License (GPL) or GNU General Public License v2 or later (GPLv2+)
  summary: 'A simple testing framework for command line applications'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
